name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # 第一个 Job：生成矩阵
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          folders=$(find . -maxdepth 1 -type d -name 'test*' | sed 's|./||')
          echo "Found folders: $folders"
        
          matrix=$(printf '{"folder": [%s]}' "$(echo $folders | jq -R -s -c 'split("\n") | map(select(length > 0))')")
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  test:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.folder }}
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ${{ matrix.folder }}
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ${{ matrix.folder }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.folder }}
          path: ${{ matrix.folder }}/playwright-report/
          retention-days: 30
